<a href="<?= htmlspecialchars($urlNewUser) ?>">Add new user</a><br>

<form action="/users" method="get">
<input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
<input type="submit" value="Search" />
</form>

<?php if (isset($messages['success'])): ?>
    <h3><?= htmlspecialchars($messages['success'][0])?></h3>
<?php endif;?>

<!-- 
<?php if (count($messages) > 0) : ?>
    <ul>
    <?php foreach ($messages as $messageType) : ?>
        <?php foreach ($messageType as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endif ?> 
-->

<?php foreach ($users as $user): ?>
    <div>
        <a href="/users/<?= htmlspecialchars($user['id']) ?>"><?= htmlspecialchars($user['name']) ?></a>
    </div>
<?php endforeach;?>

<br>

<div>
<a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>">Prev</a> <a href="?page=<?= $page + 1 ?>">Next</a>
</div>