<a href="/users/new">New User</a>

<form action="/users" method="get">
<input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
<input type="submit" value="Search" />
</form>

    <?php foreach ($users as $user) : ?>
        <div>
            <a href="/users/<?= htmlspecialchars($user['Id']) ?>"><?= htmlspecialchars($user['Name']) ?></a>
        </div>
    <?php endforeach ?>
<a href="/users"><h1>🔙</h1></a>
