<a href="<?= htmlspecialchars($urlNewUser) ?>">New User</a>

<form action="/users" method="get">
<input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
<input type="submit" value="Search" />
</form>

    <?php foreach ($users as $user) : ?>
        <div>
            <a href="/users/<?= htmlspecialchars($user['id']) ?>"><?= htmlspecialchars($user['name']) ?></a>
        </div>
    <?php endforeach ?>
<a href="<?= htmlspecialchars($urlUsers) ?>"><h1>🔙</h1></a>
