<?php if (count($messages) > 0) : ?>
    <ul>
    <?php foreach ($messages as $messageType) : ?>
        <?php foreach ($messageType as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endif ?> 

<?php if (isset($user)) : ?>
    <?php foreach ($user as $key => $value) : ?>
        <div>
            <strong><?= htmlspecialchars($key) ?></strong>: <?= htmlspecialchars($value) ?>
        </div>
    <?php endforeach; ?>
<?php endif ?>
<br>
    <a href="/users/<?= $user['id'] ?>/edit">Edit name</a><br>
<br>
    <a href="/users">Go back</a><br>
<br>

<form action="/users/<?= $user['id'] ?>" method="post">
      <input type="hidden" name="_METHOD" value="DELETE">
      <input type="submit" value="Delete">
    </form>
  </div>
